---
apiVersion: bootes.io/v1
kind: Cluster
metadata:
  name: cluster-1
  namespace: envoy
spec:
  config:
    name: cluster-1
    connect_timeout: 1s
    type: EDS
    lb_policy: ROUND_ROBIN
    eds_cluster_config:
      eds_config:
        resource_api_version: V3
        ads: {}

---
apiVersion: bootes.io/v1
kind: Cluster
metadata:
  name: cluster-2
  namespace: envoy
spec:
  workloadSelector:
    labels:
      app: envoy
  config:
    name: cluster-2
    connect_timeout: 1s
    type: EDS
    lb_policy: ROUND_ROBIN
    eds_cluster_config:
      eds_config:
        resource_api_version: V3
        ads: {}
