---
apiVersion: bootes.io/v1
kind: Listener
metadata:
  name: listener-1
  namespace: envoy
spec:
  config:
    name: listener_1
    address:
      socket_address:
        address: 127.0.0.1
        port_value: 10000
    filter_chains:
      - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              stat_prefix: ingress_http
              codec_type: AUTO
              rds:
                route_config_name: route-1
                config_source:
                  ads: {}
                  resource_api_version: V3
              http_filters:
                - name: envoy.filters.http.router
