---
apiVersion: skaffold/v2beta11
kind: Config
build:
  artifacts:
    - image: bootes
      docker:
        dockerfile: ./Dockerfile
  tagPolicy:
    gitCommit: {}
  local:
    concurrency: 1

deploy:
  kubectl:
    manifests:
      - ./dev/skaffold/pod.yaml
  logs:
    prefix: container
