---
apiVersion: skaffold/v2alpha3
kind: Config
build:
  artifacts:
    - image: bootes
      docker:
        dockerfile: ./Dockerfile

deploy:
  kubectl:
    manifests:
      - ./dev/skaffold/pod.yaml
