apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bootes-manager
rules:
- apiGroups:
  - bootes.io
  resources:
  - clusters
  - listeners
  - routes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bootes.io
  resources:
  - clusters/status
  - listeners/status
  - routes/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bootes-pod-reader
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bootes-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bootes-manager
subjects:
- kind: ServiceAccount
  name: default
  namespace: bootes # {"$ref":"#/definitions/io.k8s.cli.setters.namespace"}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bootes-pod-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bootes-pod-reader
subjects:
- kind: ServiceAccount
  name: default
  namespace: bootes # {"$ref":"#/definitions/io.k8s.cli.setters.namespace"}
