---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: prometheus
spec:
  type: ClusterIP
  selector:
    app: prometheus
  ports:
    - name: query
      protocol: TCP
      port: 9090
      targetPort: 9090

---
apiVersion: v1
kind: Pod
metadata:
  name: prometheus
  namespace: prometheus
  labels:
    app: prometheus
spec:
  containers:
    - name: prometheus
      image: prom/prometheus:v2.17.1
      volumeMounts:
        - name: config
          mountPath: /etc/prometheus
  volumes:
    - name: config
      configMap:
        name: config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval:     15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'bootes'
        static_configs:
          - targets: ['localhost:4000']
