---
apiVersion: v1
kind: Service
metadata:
  name: bootes
  namespace: bootes
spec:
  type: ClusterIP
  selector:
    app: bootes
  ports:
    - name: grpc
      protocol: TCP
      port: 5000
      targetPort: 5000
    - name: http-metrics
      protocol: TCP
      port: 4000
      targetPort: 4000
