---
name: CI

on:
  push:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-20.04
    container:
      image: golang:1.17.5-buster

    steps:
      - uses: actions/checkout@v2

      - name: Cache go modules
        uses: actions/cache@v2
        with:
          path: /go/pkg/mod
          key: go-mod-${{ hashFiles('go.sum') }}

      - name: Cache dev tools
        uses: actions/cache@v2
        with:
          path: dev/bin
          key: dev-tools

      - name: Fmt
        run: make fmt

      - name: Lint
        run: make lint

  test:
    runs-on: ubuntu-20.04
    container:
      image: golang:1.17.5-buster
    steps:
      - uses: actions/checkout@v2

      - name: Cache dev tools
        uses: actions/cache@v2
        with:
          path: dev/bin
          key: dev-tools

      - name: Cache go modules
        uses: actions/cache@v2
        with:
          path: /go/pkg/mod
          key: go-mod-${{ hashFiles('go.sum') }}

      - name: Test
        run: make test

  build:
    runs-on: ubuntu-20.04
    container:
      image: golang:1.17.5-buster

    steps:
      - uses: actions/checkout@v2

      - name: Cache go modules
        uses: actions/cache@v2
        with:
          path: /go/pkg/mod
          key: go-mod-${{ hashFiles('go.sum') }}

      - name: Build
        run: go build -o bootes .

  image:
    if: github.ref == 'refs/heads/main'
    needs:
      - lint
      - test
      - build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set Tag
        id: tag
        run: |
          echo ::set-output name=value::$(git rev-parse --short HEAD)

      - name: Build and Push Image
        uses: docker/build-push-action@v1
        with:
          cache_froms: 110y/bootes:latest
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: 110y/bootes
          tags: latest,${{ steps.tag.outputs.value }}
          push: true
