---
name: CI

on:
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-18.04
    container:
      image: golang:1.14.2-buster
    steps:
      - uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v1
        with:
          path: /go/pkg/mod
          key: go-mod-${{ hashFiles('go.sum') }}

      - name: Dependencies
        run: make kubebuilder

      - name: Test
        run: make test
