---
apiVersion: bootes.io/v1
kind: Cluster
metadata:
  name: cluster-1
  namespace: envoy
spec:
  config:
    name: cluster-1
    connect_timeout: 1s
    type: LOGICAL_DNS
    lb_policy: ROUND_ROBIN
    http2_protocol_options: {}
    load_assignment:
      cluster_name: cluster-1
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: cluster-1.test.svc.cluster.local
                    port_value: 10000

---
apiVersion: bootes.io/v1
kind: Cluster
metadata:
  name: cluster-2
  namespace: envoy
spec:
  workloadSelector:
    labels:
      app: envoy
  config:
    name: cluster-2
    connect_timeout: 1s
    type: LOGICAL_DNS
    lb_policy: ROUND_ROBIN
    http2_protocol_options: {}
    load_assignment:
      cluster_name: cluster-2
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: cluster-2.test.svc.cluster.local
                    port_value: 10000
