---
apiVersion: v1
kind: Pod
metadata:
  name: bootes
  namespace: bootes
  labels:
    app: bootes
spec:
  containers:
    - name: bootes
      image: bootes
      env:
        - name: XDS_GRPC_PORT
          value: "8081"
        - name: XDS_GRPC_ENABLE_CHANNELZ
          value: 'true'
        - name: XDS_GRPC_ENABLE_REFLECTION
          value: 'true'
